agents:
- description: null
  tags: null
  v2_config:
    community: public
    enabled: true
  v3_config:
    enabled: true
    users_access:
    - auth_phrase: 'kokoloko'
      auth_type: sha
      enc_phrase: null
      enc_type: none
      engine_id: '323452345363435'
      security_level: auth
      user_name: u_snmp
    - auth_phrase: 'kokoloko'
      auth_type: sha
      enc_phrase: "lokokoko"
      enc_type: aes
      engine_id: '3624356345643674567'
      security_level: private
      user_name: u_snmmp3
traps:
- description: null
  enabled: true
  server_ip: 10.0.123.1
  source_interface: controller 1
  tags: null
  v2_config:
    community: g235345345
  v3_config: null
  version: v2
- description: null
  enabled: true
  server_ip: 10.0.123.1
  source_interface: controller 1
  tags: null
  v2_config: null
  v3_config:
    user_access:
      auth_phrase: "kokoloko"
      auth_type: sha
      enc_phrase: null
      enc_type: none
      engine_id: '3423543534'
      security_level: auth
      user_name: u_snmp
  version: v3

